AFriendsOpinion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from friend_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^friend_app/', include('friend_app.urls')),
]

friend_app/urls.py
from django.conf.urls import url
from friend_app import views


app_name= 'friend_app'

urlpatterns = [
    url(r'^entry_form/$', views.entry_form, name='entry_form'),
    url(r'^output_result/$', views.OutputView.as_view(), name='output_result'),
    url(r'^thank/$', views.thankyou, name='thank'),
]

friend_app/models.py
from django.db import models

# Create your models here.
class Sentiment(models.Model):
    text = models.TextField()
    category = models.CharField(max_length=20)
    intensity = models.FloatField()

    def __str__(self):
        # return ('%s\t%s\t%s' % (self.text, self.category, self.intensity))
        return ('%s'%({
        'text': self.text, 'category': self.category, 'intensity': self.intensity
        }))

friend_app/forms.py
from django.forms import ModelForm
from friend_app import models

class SentimentForm(ModelForm):
    class Meta:
        model = models.Sentiment
        fields = ('text',)

friend_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from friend_app.models import Sentiment
from friend_app.forms import SentimentForm
from django.views.generic import View, TemplateView, DetailView
import pandas as pd
import pickle
import os

if os.path.getsize('cmodel.pkl') > 0:
    category_model_pkl = open('cmodel.pkl', 'rb')
    category_model = pickle.load(category_model_pkl)
    print(category_model)
if os.path.getsize('imodel.pkl') > 0:
    intensity_model_pkl = open('imodel.pkl', 'rb')
    intensity_model = pickle.load(intensity_model_pkl)


class IndexView(TemplateView):
    template_name = 'friend_app/index.html'


class OutputView(TemplateView):
    template_name = 'friend_app/output_result.html'
    


def entry_form(request):
    form = SentimentForm()
    if request.method == 'POST':
        form = SentimentForm(request.POST)

        if form.is_valid():
            form.save(commit=False)
            text = form.cleaned_data['text']
            sentiment = category_model.predict([text])
            intensity = intensity_model.predict([text])
            print("The predicted category is: {}".format(sentiment[0]))
            print("predicted intensity is: {}".format(intensity[0]))
            return render(request,'friend_app/output_result.html',{'text': text, 'category':sentiment[0], 'intensity': intensity[0]})

    return render(request, 'friend_app/entry_form.html', {'form': form})


def thankyou(request):
    return render(request, 'friend_app/thank.html')

friend_app/templates/friend_app/entry_form.html
<!DOCTYPE html>
{% load staticfiles %}


<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'friend_app/css/app.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <body onload="myFunction()">
  <body onload="myFunction()" style="margin:0;">
    <canvas id="c"></canvas>
    <div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">
        <div class="container base">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" name="btn btn-primary btn-lg" value="Submit">
        </form>
      </div>
    </div>
  </body>
  <script type="text/javascript" src="{% static 'friend_app/js/app.js' %}"></script>
</html>

friend_app/templates/friend_app/index.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'friend_app/css/app.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <body onload="myFunction()">
  <body onload="myFunction()" style="margin:0;">
    <canvas id="c"></canvas>
    <div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">
      <div class="container base">
        <h2>Hi there!</h2>
        <h3>My name is khan and I can deduce how you're feeling by your tweets/texts!</h3>
        <h3>We all look for that one friend's opinion before we send an important message/email/text</h3>
        <h3>to our crush...hehe.. or boss or recruiter...anyone</h3>
        <h3>Well, I am trained to be that friend of yours!</h3>
        <h3>I'll try to tell you if you seem too angry, desperate or etc in your text and let's see if I am right.</h3>
        <h3>I'd apologise beforehand if I am wrong...I am still learning and you are helping me!</h3>
        <a id="go" href="{% url 'friend_app:entry_form' %}" type="button" class="btn btn-outline-secondary btn-lg"><h1><em>Let's Go?!</em></h1></a>
      </div>
    </div>
  </body>
  <script type="text/javascript" src="{% static 'friend_app/js/app.js' %}"></script>
</html>

friend_app/templates/friend_app/output_result.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'friend_app/css/app.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <body onload="myFunction()">
  <body onload="myFunction()" style="margin:0;">
    <canvas id="c"></canvas>
    <div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">
        <div class="container base output">
          <div class="jumbotron-fluid">
            <h3>According to me, what you typed is pure <em>{{category}}</em></h3>
            <h3>As a matter of fact, on a scale of 0 to 1 with 1 being feeling strongly, you are on a {{intensity}}</h3>
            <a href="{% url 'friend_app:thank' %}"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a>
            <a href="{% url 'index' %}"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></a>
          </div>
      </div>
    </div>
  </body>
  <script type="text/javascript" src="{% static 'friend_app/js/app.js' %}"></script>
</html>

friend_app/templates/friend_app/thank.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'friend_app/css/app.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <body onload="myFunction()">
  <body onload="myFunction()" style="margin:0;">
    <canvas id="c"></canvas>
    <div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">
        <div class="container base output">
          <div class="jumbotron-fluid">
            <h3>Thankyou, hope that I was helpful!</h3>
            <h3>As of right now, I'm only 82% accurate</h3>
            <h3>Oneday, I'll be able to learn just like your bestfriend!</h3>
            <a href="{% url 'friend_app:entry_form' %}" class="btn btn-secondary th"><h3>Let's do it again!</h3></a>
            <a href="{% url 'index' %}" class="btn btn-secondary th"><h3>Maybe Later</h3></a>
          </div>
      </div>
    </div>
  </body>
  <script type="text/javascript" src="{% static 'friend_app/js/app.js' %}"></script>
</html>